openapi: 3.0.1
info:
  title: "API"
  version: "0.1.0"
  license:
    name: MIT license
security:
  - name:
    - auth
paths:
  /version:
    get:
      summary: OpenCocktail version
      description: The version of the OpenCocktail database backend
      operationId: getVersion
      security: []
      responses:
        200:
          description: The plain semantic version number as a string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'

  /cocktail:
    post:
      summary: Insert a new cocktail
      operationId: insertCocktail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cocktail'
      responses:
        201:
          description: The created cocktail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cocktail'
    get:
      summary: Search for a cocktail
      operationId: searchCocktail
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: category
          description: A cocktail category ID
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          description: A list of matching cocktails
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cocktail'
  /cocktail/{id}:
    parameters:
      - name: id
        description: The ID of a cocktail
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a cocktail by its ID
      operationId: getCocktail
      responses:
        200:
          description: The requested cocktail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cocktail"
        404:
          $ref: "#/components/responses/NotFound"
    put:
      summary: Update a cocktail
      operationId: updateCocktail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cocktail'
      responses:
        200:
          description: The updated cocktail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cocktail'
        404:
          $ref: "#/components/responses/NotFound"

  /cocktail/category:
    post:
      summary: Insert a new cocktail category
      operationId: insertCocktailCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CocktailCategory'
      responses:
        201:
          description: The created cocktail category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CocktailCategory'
    get:
      summary: Search for a cocktail category
      operationId: searchCocktailCategory
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: A list of matching cocktail categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CocktailCategory'
  /cocktail/category/{id}:
    parameters:
      - name: id
        description: The ID of a cocktail category
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a cocktail category by its ID
      operationId: getCocktailCategory
      responses:
        200:
          description: The requested cocktail category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CocktailCategory"
        404:
          $ref: "#/components/responses/NotFound"
    put:
      summary: Update a cocktail category
      operationId: updateCocktailCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CocktailCategory'
      responses:
        200:
          description: The updated cocktail category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CocktailCategory'
        404:
          $ref: "#/components/responses/NotFound"

  /ingredient:
    post:
      summary: Insert a new ingredient
      operationId: insertIngredient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingredient'
      responses:
        201:
          description: The created ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
    get:
      summary: Search for an ingredient
      operationId: searchIngredient
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: category
          description: An ingredient category ID
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          description: A list of matching ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
  /ingredient/{id}:
    parameters:
      - name: id
        description: The ID of an ingredient
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get an ingredient by its ID
      operationId: getIngredient
      responses:
        200:
          description: The requested ingredient
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ingredient"
        404:
          $ref: "#/components/responses/NotFound"
    put:
      summary: Update an ingredient
      operationId: updateIngredient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ingredient'
      responses:
        200:
          description: The updated ingredient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        404:
          $ref: "#/components/responses/NotFound"

  /ingredient/category:
    post:
      summary: Insert a new ingredient category
      operationId: insertIngredientCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientCategory'
      responses:
        201:
          description: The created ingredient category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientCategory'
    get:
      summary: Search for an ingredient category
      operationId: searchIngredientCategory
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: A list of matching ingredient categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IngredientCategory'
  /ingredient/category/{id}:
    parameters:
      - name: id
        description: The ID of an ingredient category
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get an ingredient category by its ID
      operationId: getIngredientCategory
      responses:
        200:
          description: The requested ingredient category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IngredientCategory"
        404:
          $ref: "#/components/responses/NotFound"
    put:
      summary: Update an ingredient category
      operationId: updateIngredientCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientCategory'
      responses:
        200:
          description: The updated ingredient category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientCategory'
        404:
          $ref: "#/components/responses/NotFound"

  /glass:
    post:
      summary: Insert a new glass
      operationId: insertGlass
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Glass'
      responses:
        201:
          description: The created glass
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Glass'
    get:
      summary: Search for a glass
      operationId: searchGlass
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: A list of matching glasses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Glass'
  /glass/{id}:
    parameters:
      - name: id
        description: The ID of a glass
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a glass by its ID
      operationId: getGlass
      responses:
        200:
          description: The requested glass
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Glass"
        404:
          $ref: "#/components/responses/NotFound"
    put:
      summary: Update a glass
      operationId: updateGlass
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Glass'
      responses:
        200:
          description: The updated glass
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Glass'
        404:
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    Version:
      type: object
      required:
        - apiVersion
        - implementation
      properties:
        apiVersion:
          example: 1.0.0
          description: The API version
          type: string
        implementation:
          $ref: "#/components/schemas/ImplementationInfo"
    ImplementationInfo:
      type: object
      description: Information about the implementation serving the API
      required:
        - name
        - version
      properties:
        name:
          example: CocktailParty
          type: string
        version:
          example: 1.0.0
          type: string
        projectInfo:
          description: URL to project website
          example: OpenCocktail.party
          type: string
    Cocktail:
      type: object
      required:
        - id
        - name
        - description
        - ingredients
        - category
        - glass
        - revisionDate
      properties:
        id:
          example: 42
          type: integer
        name:
          example: Tequila Sunrise
          type: string
        description:
          example: Resembles a beautiful sunrise
          type: string
        ingredients:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/Ingredient"
              - type: array
                items:
                  $ref: "#/components/schemas/Ingredient"
        category:
          $ref: "#/components/schemas/CocktailCategory"
        glass:
          $ref: "#/components/schemas/Glass"
        imageLink:
          example: https://exampleimage.link
          type: string
        revisionDate:
          type: string
          format: date
        notes:
          example: This is a note on a cocktail
          type: string
    Ingredient:
      type: object
      required:
        - id
        - name
        - share
        - alcoholPercentage
        - category
      properties:
        id:
          example: 123
          type: integer
        name:
          example: Sierra Silver Tequila
          type: string
        share:
          example: 20
          type: integer
          format: int32
          minimum: 0
          maximum: 100
        imageLink:
          example: https://exampleimage.link
          type: string
        alcoholPercentage:
          example: 38
          type: integer
          format: int32
        category:
          "$ref": "#/components/schemas/IngredientCategory"
        notes:
          example: This is a note on an ingredient
          type: string
    CocktailCategory:
      type: object
      required:
        - id
        - name
        - description
      properties:
        id:
          example: 123
          type: integer
        name:
          example: Basics
          type: string
        description:
          example: Cocktails everybody knows
          type: string
        imageLink:
          example: https://exampleimage.link
          type: string
    IngredientCategory:
      type: object
      required:
        - id
        - name
        - alcoholic
      properties:
        id:
          example: 123
          type: integer
        name:
          example: Tequila
          type: string
        alcholic:
          example: true
          type: boolean
        imageLink:
          example: https://exampleimage.link
          type: string
    Glass:
      type: object
      required:
        - id
        - name
        - estimatedSize
      properties:
        id:
          example: 123
          type: integer
        name:
          example: Collins glass
          type: string
        estimatedSize:
          example: 400
          description: Typical glass size in milliliters
          type: integer
          format: int32
        imageLink:
          example: https://exampleimage.link
          type: string

  responses:
    NotFound:
      description: The cocktail does not exist
      content:
        application/json:
          schema:
            example: Not found
            type: string
    SemanticError:
      description: The request contained semantic errors
      content:
        application/json:
          schema:
            example: Unprocessable Entity
            type: string

  securitySchemes:
    auth:
      type: apiKey
      description: An API key issued by server
      name: ApiKey
      in: header
