DROP SEQUENCE IF EXISTS cocktail_category_id_seq CASCADE;
DROP SEQUENCE IF EXISTS cocktail_id_seq CASCADE;
DROP SEQUENCE IF EXISTS glass_id_seq CASCADE;
DROP SEQUENCE IF EXISTS ingredient_category_id_seq CASCADE;
DROP SEQUENCE IF EXISTS ingredient_id_seq CASCADE;
DROP SEQUENCE IF EXISTS accessory_id_seq CASCADE;
DROP SEQUENCE IF EXISTS accessory_category_id_seq CASCADE;
